apiVersion: v1
kind: Secret
metadata:
  name: pulumi-stack-secret
type: Opaque
stringData:
  secret: super-secret
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: nginx-k8s-stack
spec:
  envRefs:
    PULUMI_CONFIG_PASSPHRASE:
      type: Secret
      secret:
        namespace: default
        name: pulumi-stack-secret
        key: secret
  stack: nginx
  backend: "file:///home/pulumi-kubernetes-operator"
  projectRepo: https://github.com/metral/pulumi-nginx
  branch: "refs/heads/master"
  destroyOnFinalize: true
  continueResyncOnCommitMatch: true
  refresh: true
  resyncFrequencySeconds: 60
